//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlquilerLibro
    {
        public int Id { get; set; }
        public string CodigoAlquiler { get; set; }
        public string FechaAlquiler { get; set; }
        public string FechaDevolucionEstimada { get; set; }
        public string FechaDevolucionReal { get; set; }
        public int ClienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
