//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idioma
    {
        public Idioma()
        {
            this.Libros = new HashSet<Libros>();
        }
    
        public int Id { get; set; }
        public string CodigoIdioma { get; set; }
        public string DescripcionIdioma { get; set; }
    
        public virtual ICollection<Libros> Libros { get; set; }
    }
}
