//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public Libros()
        {
            this.DetalleAutors = new HashSet<DetalleAutor>();
            this.CopiaLibroes = new HashSet<CopiaLibro>();
        }
    
        public int Id { get; set; }
        public string CodigoLibro { get; set; }
        public string Titulo { get; set; }
        public string ISPN { get; set; }
        public int EditorialId { get; set; }
        public int EditorialId1 { get; set; }
        public int MateriaId { get; set; }
        public int IdiomaId { get; set; }
    
        public virtual Editorial Editorial { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual ICollection<DetalleAutor> DetalleAutors { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual ICollection<CopiaLibro> CopiaLibroes { get; set; }
    }
}
