//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mModeloContainer : DbContext
    {
        public mModeloContainer()
            : base("name=ModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Libros> Libros { get; set; }
        public DbSet<Editorial> Editorials { get; set; }
        public DbSet<Materia> Materias { get; set; }
        public DbSet<Autor> Autors { get; set; }
        public DbSet<DetalleAutor> DetalleAutors { get; set; }
        public DbSet<Idioma> Idiomas { get; set; }
        public DbSet<CopiaLibro> CopiaLibroes { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<TipoCliente> TipoClientes { get; set; }
        public DbSet<AlquilerLibro> AlquilerLibroes { get; set; }
    }
}
