//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloContainer : DbContext
    {
        public ModeloContainer()
            : base("name=ModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Libros> iLibros { get; set; }
        public virtual DbSet<Editorial> iEditorials { get; set; }
        public virtual DbSet<Materia> iMaterias { get; set; }
        public virtual DbSet<Autor> iAutors { get; set; }
        public virtual DbSet<DetalleAutor> iDetalleAutors { get; set; }
        public virtual DbSet<Idioma> iIdiomas { get; set; }
        public virtual DbSet<CopiaLibro> iCopiaLibroes { get; set; }
        public virtual DbSet<Cliente> iClientes { get; set; }
        public virtual DbSet<TipoCliente> iTipoClientes { get; set; }
        public virtual DbSet<AlquilerLibro> iAlquilerLibroes { get; set; }
    }
}
